# Generated by Django 5.1.4 on 2024-12-16 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user2cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='summaries', to='calcus.category')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses', to='calcus.category')),
                ('friend', models.ManyToManyField(related_name='expenses', to='calcus.user2cal')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100000)),
                ('per_head_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100000)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('dateofBill', models.DateField()),
                ('entrydate', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_cate', to='calcus.category')),
                ('name', models.ManyToManyField(related_name='bill2fnd', to='calcus.user2cal')),
                ('paidby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paybyfnd', to='calcus.user2cal')),
            ],
        ),
    ]
