# Generated by Django 5.1.4 on 2024-12-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='per_head_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
    ]
