# Generated by Django 5.1.4 on 2024-12-17 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcus', '0002_alter_bill_billed_amount_alter_bill_per_head_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
