# Generated by Django 5.1.4 on 2024-12-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcus', '0003_alter_bill_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True)),
                ('entrydate', models.DateTimeField(auto_now_add=True)),
                ('ToBill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='make_contibuation_to_bill', to='calcus.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_make_contribution', to='calcus.user2cal')),
            ],
        ),
        migrations.CreateModel(
            name='Recived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True)),
                ('entrydate', models.DateTimeField(auto_now_add=True)),
                ('PayedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_bill_to_him', to='calcus.user2cal')),
                ('RecivedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recided_bill_by', to='calcus.user2cal')),
                ('ToBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_back_to_bill', to='calcus.bill')),
            ],
        ),
    ]
